language: java

os: linux
dist: trusty

addons:
  hosts:
    - jbake-builder
  hostname: jbake-builder

matrix:
    include:
      - jdk: oraclejdk9
      - jdk: oraclejdk8
      - jdk: openjdk8
      - jdk: openjdk7
        dist: precise
      - os: osx

before_install:
  - unset _JAVA_OPTIONS

install: true

script:
  - ./gradlew check -i

after_success:
  - ./gradlew -PskipSigning jacocoRootReport coveralls || ./gradlew clean

after_failure:
  - ./gradlew clean check --debug

notifications:
  irc: "irc.freenode.org#jbake"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d332fabb02dba68a36b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
