language: java

os: linux
dist: focal

addons:
  hosts:
  - jbake-builder
  hostname: jbake-builder

before_install:
  - unset _JAVA_OPTIONS

install: true

script:
- "./gradlew check --stacktrace"

jobs:
  include:

  - jdk: openjdk21

  - jdk: openjdk17

  - jdk: openjdk11

  - os: osx
    osx_image: xcode13.2 # defaults to openjdk17

# below config fails
#  - os: osx
#    osx_image: xcode9.4
#    jdk: openjdk11

#  - stage: Quality Check
#    name: sonarqube
#    jdk: openjdk11
#    script:
#    - "./gradlew jacocoRootReport sonarqube -i --stacktrace"
#
#  - stage: Quality Check
#    name: coveralls
#    jdk: openjdk11
#    script:
#    - "./gradlew -PskipSigning jacocoRootReport coveralls -i --stacktrace"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d332fabb02dba68a36b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
     - "$HOME/.m2/repository"
     - "$HOME/.gradle/caches/"
     - "$HOME/.gradle/wrapper/"
     - "$HOME/.sonar/cache"
     - ".gradle"
     - "build"
