version: 1
update_configs:

  - package_manager: "java:gradle"
    directory: "/jbake-core"
    update_schedule: "monthly"

  - package_manager: "java:gradle"
    directory: "/jbake-dist"
    update_schedule: "monthly"

  - package_manager: "java:maven"
    directory: "/jbake-core"
    update_schedule: "monthly"

  - package_manager: "java:maven"
    directory: "/jbake-dist"
    update_schedule: "monthly"

